# analysis_options.yaml
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/**"
    - "example/**"
    - "packages/**"

linter:
  rules:
    lines_longer_than_80_chars: false
