name: neat_form
description: A clean, lightweight, type-safe form state management and validation library for Flutter & Dart.
version: 1.2.3
homepage: https://github.com/datnguyennt/neat_form
repository: https://github.com/datnguyennt/neat_form
issue_tracker: https://github.com/datnguyennt/neat_form/issues

topics:
  - forms
  - validation
  - form-validation
  - state-management
  - riverpod

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0
