name: neat_form
description: A clean, lightweight, type-safe form state management and validation library for Dart & Flutter.
version: 1.0.0
homepage: https://github.com/datnguyen/neat_form
repository: https://github.com/datnguyen/neat_form

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
